/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as ColeccionesRouteImport } from './routes/colecciones'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductosIdRouteImport } from './routes/productos.$id'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccionesRoute = ColeccionesRouteImport.update({
  id: '/colecciones',
  path: '/colecciones',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIdRoute = ProductosIdRouteImport.update({
  id: '/productos/$id',
  path: '/productos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/colecciones': typeof ColeccionesRoute
  '/editorial': typeof EditorialRoute
  '/ofertas': typeof OfertasRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/tienda': typeof TiendaRoute
  '/productos/$id': typeof ProductosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/colecciones': typeof ColeccionesRoute
  '/editorial': typeof EditorialRoute
  '/ofertas': typeof OfertasRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/tienda': typeof TiendaRoute
  '/productos/$id': typeof ProductosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/colecciones': typeof ColeccionesRoute
  '/editorial': typeof EditorialRoute
  '/ofertas': typeof OfertasRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/tienda': typeof TiendaRoute
  '/productos/$id': typeof ProductosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/colecciones'
    | '/editorial'
    | '/ofertas'
    | '/order-confirmed'
    | '/tienda'
    | '/productos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/colecciones'
    | '/editorial'
    | '/ofertas'
    | '/order-confirmed'
    | '/tienda'
    | '/productos/$id'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/colecciones'
    | '/editorial'
    | '/ofertas'
    | '/order-confirmed'
    | '/tienda'
    | '/productos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ColeccionesRoute: typeof ColeccionesRoute
  EditorialRoute: typeof EditorialRoute
  OfertasRoute: typeof OfertasRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  TiendaRoute: typeof TiendaRoute
  ProductosIdRoute: typeof ProductosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecciones': {
      id: '/colecciones'
      path: '/colecciones'
      fullPath: '/colecciones'
      preLoaderRoute: typeof ColeccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$id': {
      id: '/productos/$id'
      path: '/productos/$id'
      fullPath: '/productos/$id'
      preLoaderRoute: typeof ProductosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ColeccionesRoute: ColeccionesRoute,
  EditorialRoute: EditorialRoute,
  OfertasRoute: OfertasRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  TiendaRoute: TiendaRoute,
  ProductosIdRoute: ProductosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
